### ISSUE TITLE
css经常遇到的问题

### ISSUE THREAD

**Issue by xiaoyuhen** [xiaoyuhen/baidu-task#2]
### 常见网页
css知识比较琐碎，在写简易网页时，也遇到了一些问题。这些问题通过摸索都能找到合适的解决方案，现在总结一下，方便以后查阅
#### 浮动居中
普通div居中很简单，直接设置
```css
div {
  margin: 0 auto;
}
```
即可
如果需要设置的div已经设置了float，那么这种方法就无法设置div为居中了。
这时候我们可以通过让最外面的层相对定位，left等于50%，然后内部嵌套层也使用相对定位且left设为-50%，这样的效果就是内层相对整行为水平居中。
具体代码如下：
```css
#wrapper {
float: left;
position: relative;
text-align: left;
left: 50%;
}
#wrapper ul {
list-style: none;
position: relative;
left: -50%;
}
#wrapper ul li {
float: left;
position: relative;
}
```

也可以参考*Matthew James Taylor*的方法：

```
.pagination {
  float: left;
  width: 100%;
  overflow: hidden;
  position: relative;
}
.pagination ul {
  clear: left;
  float: left;
  position: relative;
  left: 50%;/*整个分页向右边移动宽度的50%*/
}
.pagination li {
  display: block;
  float: left;
  position: relative;
  right: 50%;/*将每个分页项向左边移动宽度的50%*/
}
```
>没有浮动的div：可以看到宽度为100%。
>![alt text](http://liuwanlin.info/content/images/2015/04/centered-menus-non-floated-div.gif)
>向左边浮动的div：宽度由div中的内容决定（除非显示设置宽度）。
>![alt text](http://liuwanlin.info/content/images/2015/04/centered-menus-left-floated-div.gif)
>标准左对齐的菜单：使用浮动将导航浮动到左边，每个分页项也浮动。
>![alt text](http://liuwanlin.info/content/images/2015/04/centered-menus-left-tabs-1.gif)
>向右移动ul：设置ul的position:relative属性，并且向右移动50%（left: 50%）。
>![alt text](http://liuwanlin.info/content/images/2015/04/centered-menus-shifted-tabs-1.gif)
>向左移动ul中的所有li：在li上也设置position:relative属性，同时向左移动50%（right: 50%）。
>![alt text](http://liuwanlin.info/content/images/2015/04/centered-menus-centered-tabs.gif)

#### vertical-align
vertical-align用来设置元素的垂直对齐方式。通过选择顶线、基线、中线、底线对齐的方式，用来设置样式。
vertical-align只有在inline-block的元素上猜起作用。如果发现使用vertical-align后还是无法改变对齐方式，可以尝试设置display元素。

#### 图片位置
为了节省流量，我们在平常设计网页时，对背景图片会使用整块切图。通过设置图片的background-position(x,y)的值，来显示想要的图片，这种方式在星级评分，老虎机等前端项目中经常会被采用。
```
background-position: 130px 0;
```
