### ISSUE TITLE
flex布局

### ISSUE THREAD

**Issue by xiaoyuhen** [xiaoyuhen/baidu-task#5]
# css布局
传统css布局主要是依据盒模型，通过display属性，position属性，float属性实现布局。对于一些特殊情况就很难实现。
比如大家经常会头疼的垂直居中，如果用盒模型的思路来设置的话，需要依赖一些hack,比如通过translate() 变形函数实现垂直居中
```css
main { 
position : absolute; 
top : 50%; left : 50%; 
transform: translate(-50%, -50%); }
```
但是通过这种方法也会实用性并不高。
# Flex布局
flex是弹性布局，比盒模型提供更大的灵活度。比如垂直居中的问题，如果通过flex解决，只需要两行声明即可
```css
body { 
display : flex; 
min-height : 100vh; 
margin : 0; 
}
main {
margin : auto; 
}
```
采用felt布局的元素，成为flex容器，flex容器可以包含多种项目。我们只需要通过设置项目的不同属性。就可以改变容器内项目的样式。
flex的布局如下：
![flex](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071004.png)
### flex-direction
决定主轴方向
![flex-direction](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071005.png)
### flex-wrap
默认情况，项目都排在一条轴线，如果轴线排不下了，怎么分布。flex-wrap就是决定这个的属性
![flex-wrap](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071006.png)
### justify-content
定义了项目在主轴上的对齐方式
### align-items
定义项目在交叉轴上如何对齐
有了这个就可以很方便的解决当时遇到的li元素对齐问题
![li](https://cloud.githubusercontent.com/assets/11402392/15991729/0943320c-30ee-11e6-8c39-94642883a4a5.png)
### align-content
定义了多根轴线的对齐方式。如果出现多个轴线，可以把一条轴线的项目看做一个项目，align-conten表示的就是多条轴线的项目整体的对齐方式
##项目属性
### order
可以定义项目的排列顺序，数值越小，排列越靠前，默认为0；
### flex-grow
定义项目放大的比例，默认为0；表示即使存在剩余空间，也不放大。如果一个项目的flex-grow为2，其他项目为1.则前者占据的剩余空间比其他的多一倍。
### flex-shrink
定义了项目的缩小比例，空间不足时，项目会缩小。如果一个项目的flex-shrink为0.其他项目为1.则当空间不足时，前者不缩小。
### align-self
允许单个项目可以有和其他项目不同的对齐方式。
## 兼容性
![兼容性](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071003.jpg)
